### ISSUE TITLE
Error when add new (first) node

### ISSUE THREAD

**Issue by testor321** [likema/docker-gluster-web-interface#1]
Hi

I get this error when I try add a node
Showing /gluster-web/app/views/node/index.html.erb where line #9 raised:
no such service echo/tcp

def ping_test?(host)       check = Net::Ping::External.new(host)       return check.ping?     end end

Rails.root: /gluster-web

Application Trace | Framework Trace | Full Trace
app/helpers/application_helper.rb:193:in `new'
app/helpers/application_helper.rb:193:in `ping_test?'
app/helpers/application_helper.rb:128:in `block in ssh_nodes'
app/helpers/application_helper.rb:120:in `ssh_nodes'
app/views/node/index.html.erb:9:in `_app_views_node_index_html_erb___1879663613896154129_100236580'

Can you help me ?
Thank you

**Comment by SeBsZ** [comment]
I got the exact same problem. How come no one else has encountered this issue?

**Comment by christianuhlmann** [comment]
@likema do you still maintain this repository?

**Comment by likema** [comment]
Sorry, I just built it to view Web UI and did not run the real business.

**Comment by alagilbert** [comment]
Is there a way to resolve this bug ?

**Comment by likema** [comment]
Fixed it by installing netbase in docker image.

Can you test it again by pulling new image?
